import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs/promises";
import path from "path";
import { watch } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outputDir = prod ? "dist" : "/Users/ruben/Library/Mobile Documents/iCloud~md~obsidian/Documents/git-notes-in-icloud/.obsidian/plugins/preso";

async function inlineFontsInCss(sourceCssPath, destinationCssPath) {
  try {
    let cssContent = await fs.readFile(sourceCssPath, "utf8");
    const urlRegex = /url\((['"]?)([^'"()]+?\.(?:otf|ttf|woff|woff2))\1\)/g;
    const matches = Array.from(cssContent.matchAll(urlRegex));

    if (matches.length > 0) {
      console.log(`Inlining fonts into ${destinationCssPath}...`);
    }

    for (const match of matches) {
      const originalUrlDeclaration = match[0];
      const fontFilePath = match[2];
      
      try {
        const fontData = await fs.readFile(fontFilePath);
        const base64Data = fontData.toString('base64');
        const fontExtension = path.extname(fontFilePath).substring(1);
        const mimeType = `font/${fontExtension}`;
        
        const dataUrl = `url(data:${mimeType};base64,${base64Data})`;
        cssContent = cssContent.replace(originalUrlDeclaration, dataUrl);
        console.log(`  ✓ Inlined ${fontFilePath}`);

      } catch (fontErr) {
        if (fontErr.code === 'ENOENT') {
          console.warn(`  ✗ Font file not found, skipping: ${fontFilePath}`);
        } else {
          throw fontErr;
        }
      }
    }

    await fs.writeFile(destinationCssPath, cssContent);
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }
}

const buildPlugin = {
    name: "build-and-copy",
    setup: (build) => {
        build.onEnd(async (result) => {
            if (result.errors.length > 0) return;
            console.log("Build succeeded, processing static files...");

            await fs.cp("manifest.json", path.join(outputDir, "manifest.json"));
            await inlineFontsInCss("styles.css", path.join(outputDir, "styles.css"));
            
            console.log(`✅ Files ready in ${outputDir}`);
        });
    },
};

const buildOptions = {
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab",
		"@codemirror/commands", "@codemirror/language", "@codemirror/lint",
		"@codemirror/search", "@codemirror/state", "@codemirror/view",
		"@lezer/common", "@lezer/highlight", "@lezer/lr", ...builtins
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outputDir, "main.js"), // Output to the correct directory
	minify: prod,
	plugins: [buildPlugin]
};

if (prod) {
    await fs.rm("dist", { recursive: true, force: true });
    await fs.mkdir("dist", { recursive: true });
	await esbuild.build(buildOptions);
} else {
	const context = await esbuild.context(buildOptions);
	await context.watch();
    
	watch("styles.css", async (event, filename) => {
		if (filename) {
			console.log(`${filename} changed, rebuilding...`);
			await context.rebuild();
		}
	});
}