import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs/promises";
import path from "path";
import { watch } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const vaultPath = "/Users/ruben/Library/Mobile Documents/iCloud~md~obsidian/Documents/git-notes-in-icloud/.obsidian/plugins/preso";
const prod = (process.argv[2] === "production");

/**
 * Reads a CSS file, finds all font url() references,
 * and replaces them with Base64-encoded data URLs.
 * @param {string} sourceCssPath - Path to the source CSS file.
 * @param {string} destinationCssPath - Path to write the modified CSS file.
 */
async function inlineFontsInCss(sourceCssPath, destinationCssPath) {
  try {
    let cssContent = await fs.readFile(sourceCssPath, "utf8");
    // Regex to find url() declarations for common font types.
    const urlRegex = /url\((['"]?)([^'"()]+?\.(?:otf|ttf|woff|woff2))\1\)/g;
    const matches = Array.from(cssContent.matchAll(urlRegex));

    if (matches.length > 0) {
      console.log("Inlining fonts in styles.css...");
    }

    for (const match of matches) {
      const originalUrlDeclaration = match[0];
      const fontFilePath = match[2];
      
      try {
        const fontData = await fs.readFile(fontFilePath);
        const base64Data = fontData.toString('base64');
        const fontExtension = path.extname(fontFilePath).substring(1);
        const mimeType = `font/${fontExtension}`;
        
        const dataUrl = `url(data:${mimeType};base64,${base64Data})`;
        cssContent = cssContent.replace(originalUrlDeclaration, dataUrl);
        console.log(`  ✓ Inlined ${fontFilePath}`);

      } catch (fontErr) {
        if (fontErr.code === 'ENOENT') {
          console.warn(`  ✗ Font file not found, skipping: ${fontFilePath}`);
        } else {
          throw fontErr;
        }
      }
    }

    await fs.writeFile(destinationCssPath, cssContent);
  } catch (err) {
    // Gracefully handle if styles.css does not exist.
    if (err.code !== 'ENOENT') throw err;
  }
}

const copyPlugin = {
  name: "copy-to-vault",
  setup: (build) => {
    build.onEnd(async (result) => {
      if (result.errors.length > 0) return;

      console.log("Build succeeded, processing final files...");
      
      // Copy essential files
      await fs.cp("main.js", path.join(vaultPath, "main.js"));
      await fs.cp("manifest.json", path.join(vaultPath, "manifest.json"));

      // Process styles.css to inline fonts instead of just copying it
      await inlineFontsInCss("styles.css", path.join(vaultPath, "styles.css"));
      
      console.log("Files copied to vault.");
    });
  },
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyPlugin]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
		await context.watch();
	// Watch styles.css and trigger a rebuild on change
	watch("styles.css", async (event, filename) => {
		if (filename) {
			console.log(`${filename} changed, rebuilding...`);
			await context.rebuild();
		}
	});
}